# fly.toml file generated for gpt-api on 2023-04-22T08:06:04+01:00

app = "gpt-api"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "hkg"

[build]
  dockerfile = "Dockerfile"

[env]
  ENVIRONMENT = "production"
  FFMPEG_PATH = "/usr/bin/ffmpeg"
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
